[package]
name = "lnshot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
clap = { version = "4.1", features = ["derive"] }
directories = "4.0"
keyvalues-serde = "0.1"
notify-debouncer-mini = "0.2"
path-matchers = "1.0"
serde = { version = "1.0", features = ["derive"] }
steamid-ng = "1.0"
steamlocate = { version = "1.1", features = ["shortcuts_extras"] }
steamy-vdf = "0.2"
symlink = "0.1"
